-- FIT3003 MAJOR ASSIGNMENT 2022
-- TASK C.3 (REPORT 1 - 4)
-- STUDENT NAME: AMY WANG JUNE KOH, CHERLINE DELFINA TANDRA
-- STUDENT ID: 29796601, 31864767
-- DATE MODIFIED: 12/10/2022

-- REPORT 1: MonCity’s cumulative number of booking records of each month for Faculty of IT
SELECT FACULTYID AS "FacultyID", BOOKINGMONTH AS "Month", SUM(NO_OF_BOOKING) AS "Total bookings",
SUM(SUM(NO_OF_BOOKING)) OVER (ORDER BY FACULTYID, TO_DATE(BOOKINGMONTH, 'MONTH')) AS "Cumulative number of booking records"
FROM BOOKING_FACT1
WHERE FACULTYID LIKE 'FIT'
GROUP BY FACULTYID, BOOKINGMONTH
ORDER BY TO_DATE(BOOKINGMONTH, 'MONTH');

-- REPORT 2: MonCity’s maintenance report
SELECT DECODE(GROUPING(M.TEAMID),1,'All Teams', M.TEAMID) AS "Team ID",
DECODE(GROUPING(C.CARBODYTYPE),1,'All Car Body Types', C.CARBODYTYPE) AS "Car body type",
SUM(M.NO_OF_MAINTENANCE) AS "Total number of maintenance",
TO_CHAR (SUM(M.TOTAL_MAINTENANCE_COST),'9,999,999,999') AS "Total maintenance cost"
FROM MAINTENANCE_FACT1 M, CAR_BODY_DIM1 C
WHERE M.CARBODYTYPE = C.CARBODYTYPE AND
M.TEAMID IN ('T002','T003')
GROUP BY CUBE(M.TEAMID, C.CARBODYTYPE)
ORDER BY "Team ID", "Car body type";

-- REPORT 3: MonCity’s rank analysis for the number of accidents
SELECT DISTINCT A.ERRORCODE AS "Error Code", REGISTRATIONNO AS "Registration No.",
A.CARBODYTYPE AS "Car body type", A.TOTAL_NUMBER_OF_ACCIDENTS AS "Total number of accidents", A."Rank" FROM (
SELECT A.ERRORCODE, CAR.REGISTRATIONNO, C.CARBODYTYPE, SUM(NO_OF_ACCIDENTS) AS TOTAL_NUMBER_OF_ACCIDENTS,
DENSE_RANK() OVER(PARTITION BY A.ERRORCODE ORDER BY SUM(NO_OF_ACCIDENTS)DESC) AS "Rank"
FROM ACCIDENT_FACT1 A, CAR_BODY_DIM1 C, ACCIDENTINFO_DIM1 AI, CARACCIDENT_BRIDGE CA, CAR_DIM CAR
WHERE A.CARBODYTYPE = C.CARBODYTYPE
AND AI.ACCIDENTID = A.ACCIDENTID
AND CA.ACCIDENTID = AI.ACCIDENTID
AND CA.REGISTRATIONNO = CAR.REGISTRATIONNO
GROUP BY A.ERRORCODE, CAR.REGISTRATIONNO, C.CARBODYTYPE) A, ACCIDENTINFO AI
WHERE A.ERRORCODE = AI.ERRORCODE
AND (UPPER(AI.CAR_DAMAGE_SEVERITY) = 'VERY MINOR DAMAGE' OR UPPER(A.ERRORCODE) = 'ERROR002')
AND A."Rank" <=3
ORDER BY A.ERRORCODE, A."Rank";

-- REPORT 4: MonCity’s booking report
SELECT C.CARBODYTYPE AS "Car body type",
DECODE(GROUPING(B.AGEGROUP),1,'All Age Groups', B.AGEGROUP) AS "Age group",
DECODE(GROUPING(B.FACULTYID),1,'All Faculties', INITCAP(B.FACULTYID)) AS "Faculty ID",
TO_CHAR(SUM(NO_OF_BOOKING),'9,999,999,999') AS "Total number of bookings"
FROM BOOKING_FACT1 B, CAR_BODY_DIM1 C
WHERE B.CARBODYTYPE = C.CARBODYTYPE AND
UPPER(C.CARBODYTYPE) LIKE 'PEOPLE MOVER'
GROUP BY C.CARBODYTYPE, ROLLUP(B.AGEGROUP), ROLLUP(B.FACULTYID)
ORDER BY "Age group", "Faculty ID", SUM(NO_OF_BOOKING) DESC;



