-- FIT3003 MAJOR ASSIGNMENT 2022
-- TASK C.1 (DATA CLEANING)
-- STUDENT NAME: AMY WANG JUNE KOH, CHERLINE DELFINA TANDRA
-- STUDENT ID: 29796601, 31864767
-- DATE MODIFIED: 12/10/2022

-- 1) RELATIONSHIP PROBLEM: ILLEGAL FACULTYID ('ALIENWARE') IN PASSENGER TABLE NOT IN FACULTY TABLE
-- CHECK
SELECT *
FROM MONCITY.PASSENGER
WHERE FACULTYID NOT IN (SELECT FACULTYID FROM   MONCITY.FACULTY);

-- FIX
DROP TABLE PASSENGER CASCADE CONSTRAINTS PURGE;
CREATE TABLE PASSENGER AS
  SELECT *
  FROM MONCITY.PASSENGER
  WHERE FACULTYID IN (SELECT FACULTYID FROM   MONCITY.FACULTY);


-- 2) INCORRECT VALUES: MAINTENANCE ID M2000 HAVE MAINTENANCE COST -200, CAN'T BE LESS THAN 0, DELETED
-- CHECK
SELECT *
FROM MONCITY.MAINTENANCE
WHERE MAINTENANCECOST < 0;

-- FIX
DROP TABLE MAINTENANCE CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCE AS
  SELECT *
  FROM   MONCITY.MAINTENANCE
  WHERE MAINTENANCECOST > 0;


-- 3) DUPLICATE PROBLEM: 2 BOOKINGID (T1218) IN MONCITY.BOOKING
-- CHECK
SELECT BOOKINGID, COUNT(*) AS DUPLICATE_RECORDS_COUNT
FROM MONCITY.BOOKING
GROUP BY BOOKINGID
HAVING COUNT (*) > 1;

-- FIX
DROP TABLE BOOKING CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKING AS
  SELECT DISTINCT *
  FROM MONCITY.BOOKING;


-- 4) NULL VALUE PROBLEM: NULL PRIMARY KEY ACCIDENTID IN MONCITY.ACCIDENTINFO
-- CHECK
SELECT *
FROM MONCITY.ACCIDENTINFO
WHERE ACCIDENTID IS NULL;

-- FIX
DROP TABLE ACCIDENTINFO CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTINFO AS
  SELECT *
  FROM MONCITY.ACCIDENTINFO
  WHERE ACCIDENTID IS NOT NULL;


-- 5) RELATIONSHIP PROBLEM: ILLEGAL ERRORCODE ('ERROR010E') IN ACCIDENTINFO TABLE NOT IN ERROR TABLE
-- CHECK
SELECT *
FROM MONCITY.ACCIDENTINFO
WHERE ERRORCODE NOT IN (SELECT ERRORCODE
FROM MONCITY.ERROR);

-- FIX
DELETE FROM ACCIDENTINFO
WHERE ERRORCODE NOT IN (SELECT ERRORCODE
FROM MONCITY.ERROR);


COMMIT; 